routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::resource('/data', 'ControllerPegawai');
// Route::get('/data/create', 'ControllerPegawai@create');
// Route::POST('/data/create', 'ControllerPegawai@store');
// Route::get('/data/{id}/edit','ControllerDepartemen@edit');
// Route::POST('/data/{id}/edit','ControllerPegawai@update');
Route::resource('/datadepartemen','ControllerDepartemen');

resources/views/create.blade.php
@extends('master/master')
@section('title', 'Tambah Data')
@section('content')
 <div class="container">
 	<div class="card">	
 		<div class="card-header">
            <div class="row">
                <div class="col">
                    <h1 align="center">Tambah Data</h1><hr>
                       <h6 align="center">Fauzan Awanda Alviansyah | 17523147</h6>            
                </div>
            </div>
 		</div>
        <form method="POST" action="/data">
            {{ csrf_field() }}
            @method('POST')
 		<div class="card-body">
                            <div class="form-group">
                                <label>Nama Depan</label>
                                <input class="form-control" type="text" name="nama_depan">
                            </div>
                            <div class="form-group">
                            	<label>Nama Belakang</label>
                            	<input type="text" class="form-control" name="nama_belakang">
                            </div>
                            <div class="form-group">
                            	<label>Tanggal Lahir</label> <br>
                            	<input type="date" class="form-control" name="tanggal_lahir" >
                            </div>
                            <div class="form-group">
	                            		<label>Jenis Kelamin</label> <br>
	                            		<div class="form-check form-check-inline">
		                                  <input class="form-check-input" type="radio" name="jenis_kelamin" value="p">
		                                  <label class="form-check-label" >Pria</label>
		                                </div>
		                                <div class="form-check form-check-inline">
		                                  <input class="form-check-input" type="radio" name="jenis_kelamin" value="w">
		                                  <label class="form-check-label" >Wanita</label>
		                                </div>
                            </div>
                            <div class="form-group">
                                <label>Alamat</label>
                                <input type="text" name="alamat" class="form-control">
                            </div>
                            <div class="form-group">
                                <label>Supervisor</label>
                                <select class="form-control" name="supervisor">
                                    @foreach($Pegawais as $pega)
                                    <option value="{{$pega->id_pegawai}}">{{$pega->nama_depan}} {{$pega->nama_belakang}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Departemen</label>
                                <select class="form-control" name="departemen">
                                    @foreach($Departemens as $depa)
                                    <option value="{{$depa->kode_departemen}}">{{$depa->nama_departemen}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Gaji</label>
                                <input type="text" name="gaji" class="form-control">
                            </div>
        </div>
        <div class="card-footer">
                    <div>
                        <button class="btn btn-success" type="submit">Submit</button>
                        <a class="btn btn-danger" href="/data">Cancel</a>
                        <a href="/data" class="btn btn-info">Liat Data</a>
                    </div>
                </div>
        </form>
 	</div>
 </div>
@endsection

resources/views/departemen.blade.php
@extends('master/master')
@section('title', 'Liat Data Departemen')
@section('content')
    <div class="container">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col">
                       <h1 align="center">Data Departemen</h1> <hr>
                       <h6 align="center">Fauzan Awanda Alviansyah | 17523147</h6>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col table-responsive">
                        <table class="table table-striped">
                            <tr>
                            	<th>No.</th>
                                <th>Kode Departemen</th>
                                <th>Nama Departemen</th>
                                <th>Nama Depan</th>
                                <th>Nama Belakang</th>
                            </tr>
                             @php
							    $no = 1;
							 @endphp
                            @foreach($Departemens as $isi)
                            <tr>
                                <td>{{$no++}}</td>
                            	<td>{{ $isi->kode_departemen }}</td>
                                <td>{{ $isi->nama_departemen }}</td> 
                                <td>{{ $isi->Manajer['nama_depan']}}</td>                               
                                <td>{{ $isi->Manajer['nama_belakang']}}</td>
                            </tr>
                            @endforeach
                        </table>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <a href="/data" class="btn btn-info">Data Pegawai</a>
            </div>
        </div>
    </div>
@endsection

resources/views/edit.blade.php
@extends('master/master')
@section('title', 'Edit Data')
@section('content')
 <div class="container">
 	<div class="raw">
 		<div class="col">
 			<br>
	 		<h1 align="center">Edit Data</h1> <hr>
                       <h6 align="center">Fauzan Awanda Alviansyah | 17523147</h6>			
 		</div>
 	</div>
 	<div class="card">	
        <form method="POST" action="/data/{{$Pegawais->id_pegawai}}">
            {{ csrf_field() }}
            @method('PUT')
 		<div class="card-body">
                            <div class="form-group">
                                <label>Nama Depan</label>
                                <input class="form-control" type="text" name="nama_depan" value="{{$Pegawais->nama_depan}}">
                            </div>
                            <div class="form-group">
                            	<label>Nama Belakang</label>
                            	<input type="text" class="form-control" name="nama_belakang" value="{{$Pegawais->nama_belakang}}">
                            </div>
                            <div class="form-group">
                            	<label>Tanggal Lahir</label> <br>
                            	<input class="form-control" type="date" name="tanggal_lahir" value="{{$Pegawais->tanggal_lahir}}">
                            </div>
                            <div class="form-group">
	                            		<label>Jenis Kelamin</label> <br>
	                            		<div class="form-check form-check-inline">
		                                  <input class="form-check-input" type="radio" name="jenis_kelamin" value="p">
		                                  <label class="form-check-label" >Pria</label>
		                                </div>
		                                <div class="form-check form-check-inline">
		                                  <input class="form-check-input" type="radio" name="jenis_kelamin" value="w">
		                                  <label class="form-check-label" >Wanita</label>
		                                </div>
                            </div>
                            <div class="form-group">
                                <label>Alamat</label>
                                <input type="text" name="alamat" class="form-control" value="{{$Pegawais->alamat}}">
                            </div>
                            <div class="form-group">
                                <label>Departemen</label>
                                <select class="form-control" name="departemen">
                                    <option value="{{$Pegawais->kode_departemen}}" readonly="">-- select --</option>
                                    @foreach($Departemens as $depa)
                                    <option value="{{$depa->kode_departemen}}">{{$depa->nama_departemen}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Gaji</label>
                                <input type="text" name="gaji" class="form-control" value="{{$Pegawais->gaji}}">
                            </div>
        </div>
        <div class="card-footer">
                    <div>
                        <button class="btn btn-success" type="submit">Update</button>
                        <a class="btn btn-danger" href="/data">Cancel</a>

                    </div>
                </div>
        </form>
 	</div>
 </div>
@endsection

resources/views/index.blade.php
@extends('master/master')
@section('title', 'Liat Data Pegawai')
@section('content')
    <div class="container">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col">
                       <h1 align="center">Data Pegawai</h1><hr>
                       <h6 align="center">Fauzan Awanda Alviansyah | 17523147</h6>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col table-responsive">
                        <table class="table table-striped">
                            <tr>
                            	<th>No.</th>
                                <th>Nama Depan</th>
                                <th>Nama Belakang</th>
                                <th>Tanggal Lahir</th>
                                <th>Jenis Kelamin</th>
                                <th>Kode Departemen</th>
                                <th>Departemen</th>
                                <th>Action</th>
                            </tr>
                             @php
							    $no = 1;
							 @endphp
                            @foreach($Pegawais as $isi)
                            <tr>
                                <td>{{$no++}}</td>
                            	<td>{{ $isi->nama_depan }}</td>
                                <td>{{ $isi->nama_belakang }}</td> 
                                <td>{{ $isi->tanggal_lahir }}</td>                               
                                <td>{{ $isi->jenis_kelamin }}</td>
                                <td>{{ $isi->departemen }}</td>
                                <td>{{ $isi->Departemen['nama_departemen']}}</td>
                                <td>
                                    <div style="display: flex;">
                                        <a class="btn btn-primary btn-sm" href="{{route('data.edit',$isi->id_pegawai)}}">Edit</a>
                                        <form class="_delete_form" style="margin-left: 2px;" action="{{ route('data.destroy', $isi->id_pegawai) }}" method="post">
                                            {{csrf_field()}} {{method_field('DELETE')}}
                                        <button class="btn btn-danger btn-sm" type="submit">Delete</button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </table>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <a href="/data/create" class="btn btn-success">Tambah Pegawai</a>
                <a href="/datadepartemen" class="btn btn-info">Data Manager</a>
            </div>
        </div>
    </div>
@endsection